#spring  setup and common configuration
spring:
  profiles:
    active: local

---
spring:
  profiles: local
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
    open-in-view: false
    properties:
      hibernate.enable_lazy_load_no_trans: true
    show-sql: true
  h2:
    console:
      path: /h2
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

# graphql config
# default endpoint 'graphql'
# if you change endpoint, graphql.servlet.mapping -> definition your endpoint
graphql:
  spqr:
    http:
      enabled: true
      endpoint: /music
    gui:
      enabled: true

#logging
logging:
  file: logs/my-logging-file.log
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
  pattern:
    # console에 찍히는 로그 형식 정의
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    # console에서 로그는 위에 형식으로 찍히지만 파일로 씌여질 때 해당 패턴으로 찍는다. 
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"